### PR TITLE
Convert projection fields option to object

### LINKED ISSUE #459: Projection fields in find and optimizedFindOrCreate must be object
# Description/Steps to reproduce

When given a fields selection object during `find` or `findOrCreate`, loopback converts it to an **array** of included fields and passes it to MongoDB library. But MongoDb library according to [find spec](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#find) and *although deprecated* [findAndModify](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#findAndModify) need a `projection` property that is an **object** and not an array.
However MongoDB library itself checks for provided array and converts it into an object but only in `find` methods of `collection.js` I guess since `findAndModify` is deprecated they did not bother adding this there.

In order to reproduce the problem, we need to use the  [optimizedFindOrCreate](https://github.com/strongloop/loopback-connector-mongodb/blob/ee24cd08b8ccc32711264831c71b1da628df357b/lib/mongodb.js#L1833) of Mongodb connector by setting the option `enableOptimizedFindOrCreate` to `true`  in MongoDB connector settings.
After that, issue a `findOrCreate` from a model that also includes a projection filter. The filter won't work

# Expected result

The arguments should be provided in the expected format of MongoDB driver. The current situation results in not getting any fields back, if you provide the projection document in a `findOrCreate` operation

# Additional information

linux x64 10.8.0
loopback-connector-mongodb@3.6.0

### PR DESCRIPTION
**Pull request by mitsos1os**
### Description
Fix provided `projection` option arguments to be provided in **object** expected format to MongoDB library. New object was created in order to avoid tampering with existing fields format that could interfere with different parts of code.

#### Related issues

- connect to #459 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by raymondfeng** [comment]
@mitsos1os The `memwatch-next` issue should be fixed on master now. Can you rebase to master?

**Comment by dhmlau** [comment]
@slnode test please.
Jenkins is still yellow after 5 hours.  Kicking off the test again.

**Comment by dhmlau** [comment]
All tests are passed.  @raymondfeng , could you please review?  Thanks.

File: lib/mongodb.js [hunk 1]
```diff
@@ -1237,8 +1256,7 @@ MongoDB.prototype.all = function all(model, filter, options, callback) {
   fields = self.fromPropertyToDatabaseNames(model, fields);
 
   if (fields) {
-    // convert the array of fields into a projection object see http://mongodb.github.io/node-mongodb-native/3.0/api/Collection.html#find
-    var findOpts = {projection: fields};
+    var findOpts = {projection: Array.isArray(fields) ? fieldsArrayToObj(fields) : fields};
```
Comment (virkt25) [inline lib/mongodb.js]: This can be simplified to `var findOpts = {projection: fieldsArrayToObj(fields)};` as `fireldsArrayToObj()` has a check to return as is for a non-array type.

File: lib/mongodb.js [hunk 2]
```diff
@@ -1876,10 +1894,14 @@ function optimizedFindOrCreate(model, filter, data, options, callback) {
 
   var sort = self.buildSort(model, filter.order, options);
 
+  var projection = filter.fields && Array.isArray(filter.fields) ?
```
Comment (virkt25) [inline lib/mongodb.js]: Same simplification as above applies here.

File: test/mongodb.test.js [hunk 3]
```diff
@@ -1406,6 +1406,37 @@ describe('mongodb connector', function() {
     });
   });
 
+  it('findOrCreate should properly support field projection (on create)', function() {
```
Comment (virkt25) [inline test/mongodb.test.js]: Can you add a similar test where `fields` is passed in as an array?

File: test/mongodb.test.js [hunk 4]
```diff
@@ -1406,6 +1406,37 @@ describe('mongodb connector', function() {
...
+        const createdPost = result[0];
+        const created = result[1];
+        created.should.be.true();
+        should.not.exist(createdPost.title);
+        should.not.exist(createdPost.content);
+        createdPost.comments.should.containDeep(['comment1', 'comment2']);
+      });
+  });
+
+  it('findOrCreate should properly support field projection (on find)', function() {
```
Comment (virkt25) [inline test/mongodb.test.js]: Can you add a similar test where `fields` is passed in as an array?

File: lib/mongodb.js (hunk 1 above)
Comment (mitsos1os) [reply lib/mongodb.js]: Done

File: lib/mongodb.js (hunk 2 above)
Comment (mitsos1os) [reply lib/mongodb.js]: done

File: test/mongodb.test.js (hunk 3 above)
Comment (mitsos1os) [reply test/mongodb.test.js]: done

File: test/mongodb.test.js (hunk 4 above)
Comment (mitsos1os) [reply test/mongodb.test.js]: done

File: lib/mongodb.js [hunk 5]
```diff
@@ -112,6 +112,25 @@ exports.initialize = function initializeDataSource(dataSource, callback) {
...
+ * Helper function to accept an array representation of fields projection and return the mongo
+ * required object notation
+ *
+ * @param {string[]} fieldsArray
+ * @returns {Object}
+ */
+function fieldsArrayToObj(fieldsArray) {
+  if (!Array.isArray(fieldsArray)) return fieldsArray; // fail safe check in case non array object created
+  return fieldsArray.length ?
+    fieldsArray.reduce(function arrayToObjectReducer(result, field) {
```
Comment (bajtos) [inline lib/mongodb.js]: Can we move this function to the outer scope (outside of `fieldsArrayToObj`), so that V8 does not have to create a new function every time `fieldsArrayToObj` is called?

```js
function fieldsArrayToObj(fieldsArray) {
  // ...
}

function arrayToObjectReducer(result, field) {
  // ...
}
```

File: test/mongodb.test.js [hunk 6]
```diff
@@ -1406,6 +1406,68 @@ describe('mongodb connector', function() {
     });
   });
 
+  it('findOrCreate should properly support field projection (on create) - object', function() {
+    const query = {where: {title: 'Kopria post'}, fields: {comments: 1}};
```
Comment (bajtos) [inline test/mongodb.test.js]: I think we should run these new tests for all connectors supporting `findOrCreate` to ensure consisten behavior across databases.

I am ok to keep those tests here for short term, to get this fix landed soon.

As the next step, I would like these tests to be moved to juggler's "manipulation" test suite, see 
[test/manipulation.test.js#L1557-L1622](https://github.com/strongloop/loopback-datasource-juggler/blob/fcac276955a58c4aabcd2b602af046f45cfc73fe/test/manipulation.test.js#L1557-L1622).

Comment (mitsos1os) [reply test/mongodb.test.js]: I agree to keep this change for the future

File: lib/mongodb.js (hunk 5 above)
Comment (mitsos1os) [reply lib/mongodb.js]: You are right. Done!

File: lib/mongodb.js [hunk 7]
```diff
@@ -127,6 +127,38 @@ const COMMAND_MAPPINGS = {
   estimatedDocumentCount: 'count',
 };
 
+exports.arrayToObjectReducer = arrayToObjectReducer;
```
Comment (bajtos) [inline lib/mongodb.js]: Let's keep `arrayToObjectReducer` as an internal implementation detail please and don't export it as public API. The less public API we have to maintain, the better for us.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
Thanks @mitsos1os  for your contribution.  Your PR has landed!
